version: '3'
services:
  my-node-app:
    image: zibomo_app
    networks:
      - my-network
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    networks:
      - my-network
    ports:
      - "27017:27017"

networks:
  my-network:
    driver: bridge
